import os
import shutil

# Base directory
base = "/Users/pausuris/Documents/Web Aurora Farmanova 73/farmanova73"

# Translation dictionaries for each language
translations = {
    "en": {
        'lang="ca"': 'lang="en"',
        "Farmàcia Nova 73 · La Garriga | Farmanova 73, posem el teu motor en solfa": "Farmàcia Nova 73 · La Garriga | Farmanova 73 – Tune your vitality engine",
        'content="Farmàcia Nova 73 a La Garriga (Ctra. Nova 73). Centre d\'alt rendiment vital: nutrició, analítiques, suplementació i seguiment personalitzat. Farmacia Garriga."': 'content="Farmàcia Nova 73 in La Garriga (Ctra. Nova 73). High-performance vitality centre: nutrition, rapid analytics, supplementation and personalised follow-up."',
        'content="Farmàcia Nova 73 · Farmanova 73, posem el teu motor en solfa"': 'content="Farmàcia Nova 73 · Farmanova 73 – Tune your vitality engine"',
        'content="Centre d\'alt rendiment vital a La Garriga. Nutrició, analítiques, suplementació. Menys medicalització, més vitalitat."': 'content="High-performance vitality centre in La Garriga. Nutrition, analytics, supplementation. Less medication, more vitality."',
        'href="styles.css"': 'href="../styles.css"',
        'src="assets/logo-icon.png"': 'src="../assets/logo-icon.png"',
        'src="assets/cat-flag.svg"': 'src="../assets/cat-flag.svg"',
        'src="assets/hero-poster.jpg"': 'src="../assets/hero-poster.jpg"',
        'src="assets/hero-video.mp4"': 'src="../assets/hero-video.mp4"',
        'src="assets/og-image.jpg"': 'src="../assets/og-image.jpg"',
        'src="assets/logo.svg"': 'src="../assets/logo.svg"',
        'src="main.js"': 'src="../main.js"',
        'src="lang-detect.js"': '',
        # Nav
        'aria-label="Farmàcia Nova 73 - Inici"': 'aria-label="Farmàcia Nova 73 - Home"',
        'aria-label="Obrir menú"': 'aria-label="Open menu"',
        '>Sobre el 73<': '>About 73<',
        '>Serveis 73 ▾<': '>Services 73 ▾<',
        '🥗 Consultoria Nutricional': '🥗 Nutritional Consulting',
        '🔬 Analítiques Ràpides': '🔬 Rapid Analytics',
        '💊 SPD Personalitzat': '💊 Personalised SPD',
        '>Qui ets tu? ▾<': '>Who are you? ▾<',
        '🔋 Motor i Energia': '🔋 Engine &amp; Energy',
        '🌸 Equilibri i Maduresa': '🌸 Balance &amp; Maturity',
        '🐣 Primers Passos': '🐣 First Steps',
        '🤝 Seguiment i Confiança': '🤝 Follow-up &amp; Trust',
        '>Reserva cita<': '>Book appointment<',
        # Hero
        'aria-label="Secció principal"': 'aria-label="Main section"',
        'Farmanova 73, posem el teu<br><em>motor en solfa</em>': 'Farmanova 73, let\'s tune your<br><em>engine</em>',
        'Som la teva farmàcia a La Garriga per a totes les etapes.<br>': 'Your pharmacy in La Garriga for every stage of life.<br>',
        'Menys medicalització, més vitalitat.': 'Less medication, more vitality.',
        'Vull posar el meu cos a punt': 'I want to get my body in shape',
        "Descobreix el nostre enfocament ↓": "Discover our approach ↓",
        '+500 garriguencs confien en el 73': '+500 people from La Garriga trust us',
        '>Explora<': '>Explore<',
        # Manifest
        'El nostre manifest': 'Our manifesto',
        'El teu cos és el lloc on viuràs tota la vida. No el teu cotxe, no la teva casa: el teu cos.\n              I com qualsevol motor de qualitat, necessita manteniment preventiu, el combustible adequat i,\n              de tant en tant, una revisió a fons.': "Your body is the place you'll live your whole life. Not your car, not your house: your body.\n              And like any quality engine, it needs preventive maintenance, the right fuel and,\n              from time to time, a thorough check-up.",
        "A la Farmàcia Nova 73 de La Garriga hem canviat el xip: no esperem que et posis malalt per\n              ajudar-te. Som el teu centre d'": "At Farmàcia Nova 73 in La Garriga we've changed the mindset: we don't wait for you to get sick to\n              help you. We're your centre of ",
        'alt rendiment vital': 'high-performance vitality',
        ", el lloc on vens quan\n              vols rendir més, sentir-te millor i envellir amb dignitat olímpica.": ", the place you come when\n              you want to perform better, feel great and age with Olympic dignity.",
        "Tenim la ciència, tenim l'experiència i, sí, tenim un punt d'humor perquè la salut no\n              ha de ser avorrida. Si ets de La Garriga i vols passar de la medicina reactiva a la\n              ": "We have the science, we have the experience and yes, we have a touch of humour because health\n              doesn't have to be boring. If you're in La Garriga and want to move from reactive medicine to\n              ",
        'vitalitat conscient': 'conscious vitality',
        ", has trobat el teu lloc al km 73.": ", you've found your place at km 73.",
        'Ciència': 'Science',
        'Evidència, no tendències': 'Evidence, not trends',
        'Persona': 'Person',
        'Tu, no el teu número': 'You, not your number',
        'Local': 'Local',
        'Arrels a La Garriga': 'Rooted in La Garriga',
        'Prevenció': 'Prevention',
        'Actuar abans que fer marxa enrere': 'Act before having to backtrack',
        # Portes
        'Per on entres?': 'Which door do you come through?',
        'Cada etapa de la vida té el seu combustible. Troba la teva porta.': 'Every stage of life has its own fuel. Find your door.',
        '>Motor i Energia<': '>Engine &amp; Energy<',
        "Esportistes, actius, gent que no vol aturar-se. Optimitza el rendiment amb nutrició esportiva, analítiques de base i suplementació intel·ligent.": "Athletes, active people, those who don't want to stop. Optimise performance with sports nutrition, baseline analytics and smart supplementation.",
        'Anàlisi composició corporal': 'Body composition analysis',
        'Nutrició esportiva personalitzada': 'Personalised sports nutrition',
        'Suplementació basada en evidència': 'Evidence-based supplementation',
        '>Optimitza el teu motor →<': '>Optimise your engine →<',
        '>Equilibri i Maduresa<': '>Balance &amp; Maturity<',
        "Maduresa activa, canvis hormonals, cuidar-se bé per seguir vivint al màxim. Perquè els 50 poden ser els nous 35.": "Active maturity, hormonal changes, taking care of yourself to keep living to the fullest. Because 50 can be the new 35.",
        'Seguiment hormonal i metabòlic': 'Hormonal and metabolic monitoring',
        "Nutrients per a l'os i el cor": 'Nutrients for bones and heart',
        "Gestió de l'energia vital": 'Vital energy management',
        '>Troba el teu equilibri →<': '>Find your balance →<',
        '>Primers Passos<': '>First Steps<',
        "Embaràs, lactància, bebès, criança. Els primers mil dies conten més del que creus. Acompanyament científic des del principi.": "Pregnancy, breastfeeding, babies, parenting. The first thousand days matter more than you think. Scientific support from the very start.",
        'Suplementació perinatal': 'Perinatal supplementation',
        'Nutrició lactació': 'Lactation nutrition',
        'Introducció alimentaria': 'Food introduction',
        ">Comença amb el peu dret →<": ">Start on the right foot →<",
        '>Seguiment i Confiança<': '>Follow-up &amp; Trust<',
        "Tens una pauta, tens medicació, vols entendre-ho tot. Aquí tens un equip que t'escolta, t'explica i fa el seguiment de debò.": "You have a treatment plan, you take medication, you want to understand it all. Here you have a team that listens, explains and truly follows up.",
        'Revisió de polimedicació': 'Polymedication review',
        'SPD (blísters personalitzats)': 'SPD (personalised blister packs)',
        'Consultes sense pressa': 'Consultations without rushing',
        ">El teu equip de confiança →<": ">Your trusted team →<",
        # Serveis
        'Els nostres serveis 73': 'Our services 73',
        'Eines concretes per a resultats reals. Ciència aplicada al teu dia a dia.': 'Concrete tools for real results. Science applied to your everyday life.',
        '>Consultoria Nutricional<': '>Nutritional Consulting<',
        "Sessió personalitzada amb la nostra farmacèutica nutricionista. Analitzem, dissenyem i fem seguiment del teu pla alimentari. Sense dietes miracle, amb ciència de debò.": "Personalised session with our nutritionist pharmacist. We analyse, design and monitor your dietary plan. No miracle diets, real science.",
        '📍 Presencial': '📍 In-person',
        ">Reserva cita →<": ">Book appointment →<",
        '>Analítiques Ràpides<': '>Rapid Analytics<',
        'Més sol·licitat': 'Most requested',
        "Resultats en minuts: glucosa, colesterol, hemoglobina, vitamina D, ferro i molt més. Interpretació farmacèutica inclosa. Sense esperar setmanes ni passes burocràtiques.": "Results in minutes: glucose, cholesterol, haemoglobin, vitamin D, iron and much more. Pharmaceutical interpretation included. No waiting weeks or bureaucratic steps.",
        '🩸 Punxada capil·lar': '🩸 Capillary puncture',
        '>Reserva ara →<': '>Book now →<',
        '>SPD Personalitzat<': '>Personalised SPD<',
        "Sistema Personalitzat de Dosificació. Tots els teus medicaments o suplements ordenats per dia i hora en blísters segells. Adéu al caos de les capses. Adéu als oblits.": "Personalised Dosage System. All your medications or supplements sorted by day and time in sealed blister packs. Goodbye to box chaos. Goodbye to forgetting.",
        '⏱ Setmanal/mensual': '⏱ Weekly/monthly',
        '🏠 Entrega a domicili': '🏠 Home delivery',
        '>Consulta SPD →<': '>Ask about SPD →<',
        # Reviews
        'El que diu La Garriga': 'What La Garriga says',
        "\"Finalment una farmàcia on et tracten com a persona, no com a número. La Marta ens va explicar tot el tema dels suplements durant l'embaràs amb una paciència infinita.\"": '"Finally a pharmacy where they treat you like a person, not a number. Marta explained all about supplements during pregnancy with infinite patience."',
        '"Porto dos anys fent les analítiques aquí. En 20 minuts tinc els resultats i l\'explicació. Increïble comparar-ho amb esperar setmanes al CAP. 100% recomanada!"': '"I\'ve been getting my analytics done here for two years. In 20 minutes I have the results and the explanation. Incredible compared to waiting weeks at the health centre. 100% recommended!"',
        '"El SPD ha canviat la vida al meu pare. Ja no s\'oblida de cap pastilla i nosaltres estem molt més tranquils. Servei excel·lent i propera."': '"The SPD changed my father\'s life. He no longer forgets any pill and we are much more at ease. Excellent and caring service."',
        '"Vaig anar amb el tema del colesterol i la tensió i em van fer un pla tan complert que el meu metge es va quedar sorprès. Professionals de veritat, amb toque humà garriguenc."': '"I went in about my cholesterol and blood pressure and they gave me such a thorough plan that my doctor was surprised. Real professionals with a human touch."',
        'Deixa la teva ressenya a Google →': 'Leave your Google review →',
        # Lead magnet
        '>El teu motor<br>en solfa<': '>Tune your<br>engine<',
        'Guia gratuïta · Farmàcia Nova 73': 'Free guide · Farmàcia Nova 73',
        '📥 PDF Gratuït': '📥 Free PDF',
        '«El teu motor en solfa»': '«Tune your engine»',
        "La nostra guia per entendre els teus biomarcadors clau, quins suplements valen la pena (i quins no) i com posar el teu cos en marxa sense complicacions.": "Our guide to understanding your key biomarkers, which supplements are worth it (and which aren't) and how to get your body going without complications.",
        '✓ Analítica bàsica: què mirar i per què': '✓ Basic analytics: what to check and why',
        '✓ Top 5 suplements sense màrqueting': '✓ Top 5 supplements without marketing hype',
        '✓ Errors nutricionals típics de La Garriga (i de tothom)': '✓ Typical nutritional mistakes (and how to fix them)',
        '✓ 7 hàbits que fan més que qualsevol pastilla': '✓ 7 habits that do more than any pill',
        '>Nom<': '>Name<',
        'placeholder="El teu nom"': 'placeholder="Your name"',
        '>Email<': '>Email<',
        "placeholder=\"el.teu@email.com\"": 'placeholder="your@email.com"',
        "Acepto la ": "I accept the ",
        "Acepto la <a href=\"privacitat.html\" target=\"_blank\">política de privacitat</a> i el tractament de les meves dades per enviar-me el PDF. *": 'I accept the <a href="privacitat.html" target="_blank">privacy policy</a> and the processing of my data to send me the PDF. *',
        "M'apunto al newsletter mensual del 73 (consells de salut, novetats, zero spam). Opcional.": "I subscribe to the monthly newsletter from 73 (health tips, news, zero spam). Optional.",
        "Tractament: Farmàcia Nova 73 (Ctra. Nova 73, La Garriga) · Finalitat: enviar PDF i, si acceptes, newsletter · Base: consentiment · Drets: accés, rectificació, supressió a ": "Controller: Farmàcia Nova 73 (Ctra. Nova 73, La Garriga) · Purpose: sending PDF and, if accepted, newsletter · Legal basis: consent · Rights: access, rectification, deletion to ",
        'Responsable: Farmàcia Nova 73.': 'Controller: Farmàcia Nova 73.',
        'Vull el meu PDF gratuït': 'I want my free PDF',
        # B2B
        '🏢 Per a empreses i gimnàs': '🏢 For businesses &amp; gyms',
        'El motor de la teva organització som nosaltres': 'We are the engine of your organisation',
        "Botiquins legals, convenis de salut per als teus empleats, tallers de nutrició per als socis del gimnàs... Fem que el teu equip rendeixi al 100%.": "Legal first-aid kits, health agreements for your employees, nutrition workshops for gym members... We make your team perform at 100%.",
        '🧰 Botiquins homologats i manteniment': '🧰 Approved first-aid kits and maintenance',
        '👥 Convenis de salut per empreses locals': '👥 Health agreements for local businesses',
        '🎤 Tallers de nutrició i benestar': '🎤 Nutrition and wellness workshops',
        '💪 Suplementació a preu conveni per gimnàs': '💪 Supplementation at agreed prices for gyms',
        'Parlem de la teva empresa →': "Let's talk about your business →",
        # Location
        'Ens trobaràs aquí': "You'll find us here",
        "Al cor de La Garriga, fàcil d'arribar i fàcil d'aparcar.": 'In the heart of La Garriga, easy to reach and easy to park.',
        '>Adreça<': '>Address<',
        '>Horaris<': '>Opening hours<',
        'Dilluns–Divendres: 9–14h · 17–20:30h<br>Dissabte: 9:30–14h': 'Mon–Fri: 9am–2pm · 5–8:30pm<br>Saturday: 9:30am–2pm',
        '>Telèfon<': '>Phone<',
        '>Email<': '>Email<',
        'Com arribar-hi →': 'Get directions →',
        '!2sca!2ses': '!2sen!2ses',
        'title="Mapa Farmàcia Nova 73 La Garriga"': 'title="Map Farmàcia Nova 73 La Garriga"',
        # Footer
        "Centre d'alt rendiment vital a La Garriga. Menys medicalització, més vitalitat.": "High-performance vitality centre in La Garriga. Less medication, more vitality.",
        '>Navega<': '>Navigate<',
        '>Sobre el 73<': '>About 73<',
        '>Serveis 73<': '>Services 73<',
        '>Empreses (B2B)<': '>Business (B2B)<',
        '>Contacte<': '>Contact<',
        '>Serveis<': '>Services<',
        '>Consultoria Nutricional<': '>Nutritional Consulting<',
        '>Analítiques Ràpides<': '>Rapid Analytics<',
        '>SPD Personalitzat<': '>Personalised SPD<',
        '>Motor i Energia<': '>Engine &amp; Energy<',
        '>Equilibri i Maduresa<': '>Balance &amp; Maturity<',
        '>Primers Passos<': '>First Steps<',
        '>Contacte<': '>Contact<',
        'Dl–Dv: 9–14h · 17–20:30h<br>Ds: 9:30–14h': 'Mon–Fri: 9am–2pm · 5–8:30pm<br>Sat: 9:30am–2pm',
        '© 2025 Farmàcia Nova 73 · La Garriga · Tots els drets reservats': '© 2025 Farmàcia Nova 73 · La Garriga · All rights reserved',
        'Política de Privacitat': 'Privacy Policy',
        '>Cookies<': '>Cookies<',
        "Avís Legal": "Legal Notice",
        # WhatsApp
        "Hola!%20Vull%20posar%20el%20meu%20motor%20en%20solfa%2C%20em%20podeu%20ajudar%20amb...%3F": "Hello!%20I%20want%20to%20tune%20my%20engine%2C%20can%20you%20help%20me%20with...%3F",
        "aria-label=\"Contacta'ns per WhatsApp\"": 'aria-label="Contact us via WhatsApp"',
        "Escriu-nos!": "Write to us!",
        # Cookies
        '🍪 Galetes i privacitat': '🍪 Cookies &amp; privacy',
        "Utilitzem cookies pròpies i de tercers per millorar la teva experiència i fer analítica web anònima.\n      Pots gestionar les teves preferències o acceptar-les totes.": "We use our own and third-party cookies to improve your experience and perform anonymous web analytics.\n      You can manage your preferences or accept them all.",
        '>Només essencials<': '>Essential only<',
        '>Acceptar totes<': '>Accept all<',
    }
}

print("Translation script ready")
print("Note: This approach has limitations with complex HTML. Using direct file write instead.")
